name: Build and Deploy Docker Image
on:
  workflow_run:
    workflows: ["Test C++ Code"] 
    branches: [master]
    types:
      - completed
  workflow_dispatch: #manually

jobs:
  docker:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Authenticate with Docker Hub now
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Create Dockerfile
        run: |
          cat > Dockerfile << 'EOF'
          FROM debian:bullseye-slim

          # Install necessary packages
          RUN apt-get update && \
              apt-get install -y --no-install-recommends \
              build-essential \
              g++ \
              libgtest-dev \
              cmake \
              && rm -rf /var/lib/apt/lists/*
          
          # Build and install Google Test
          WORKDIR /usr/src/gtest
          RUN cmake . && \
              make && \
              cp lib/*.a /usr/lib
          
          # Copy the application
          WORKDIR /app
          COPY ./binaryradix/binaryradix.cpp ./binaryradix/binaryradix_test.cpp ./binaryradix/
          WORKDIR /app/binaryradix
          
          # Compile the application
          RUN g++ -o run_tests binaryradix_test.cpp binaryradix.cpp -lgtest -lgtest_main -pthread
          
          # Set the entry point
          ENTRYPOINT ["./run_tests"]
          EOF
          
      - name: Build and push Docker image for ${{ matrix.platform }}
        uses: docker/build-push-action@v4 
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: damijanak/binaryradix:latest


