name: Build and Deploy Docker Image
on:
  workflow_run:
    workflows: ["Test C++ Code"]  
    branches: [master]
    types:
      - completed
  workflow_dispatch: #manually


jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  
    runs-on: self-hosted
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]  # multi platform
    
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2  # For cross-platform builds
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # For multi-platform builds
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Authenticate with Docker Hub now
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Create Dockerfile
        run: |
          cat > Dockerfile << 'EOF'
          FROM ubuntu:latest
          
          # Install dependencies
          RUN apt-get install -y \
              build-essential \
              g++
          
          # Copy the application
          WORKDIR /app
          COPY binaryradix.cpp .
          
          # Compile the application
          RUN g++ -o binaryradix binaryradix.cpp
          
          # Set the entry point
          ENTRYPOINT ["/app/binaryradix"]
          EOF
          
      - name: Build and push Docker image for ${{ matrix.platform }}
        uses: docker/build-push-action@v4 
        with:
          context: .
          platforms: ${{ matrix.platform }}
          push: true
          tags: yourusername/yourrepo:latest-${{ matrix.platform }}
