name: Test C++ Code
on:
  push:
    branches: [master]
  workflow_dispatch: # manually

jobs:
  check_tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: List directory contents
        run: find . -type f -name "*.cpp" | sort
        
      - name: Check if tests exist
        run: |
          if [ ! -f "binaryradix/binaryradix_test.cpp" ]; then
            echo "Error: binaryradix_test.cpp doesn't exist" >&2
            exit 1
          fi
          
          if [ ! -f "binaryradix/binaryradix.cpp" ]; then
            echo "Error: binaryradix.cpp doesn't exist" >&2
            exit 1
          fi
        continue-on-error: true
      
      - name: Redirect stderr to file
        run: ls -la binaryradix/binaryradix_test.cpp 2> napaka.txt || true
      
      - name: Upload error file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: error-log
          path: napaka.txt
          
      - name: Check test status and create status artifact
        run: |
          if [ -s napaka.txt ]; then
            echo "FAILED" > test_status.txt
          else
            echo "PASSED" > test_status.txt
          fi
      
      - name: Upload test status as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-status
          path: test_status.txt

  run-tests:
    needs: check_tests
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: Download errorlog
        uses: actions/download-artifact@v4
        with:
          name: error-log
      
      - name: Download test status
        uses: actions/download-artifact@v4
        with:
          name: test-status
      
      - name: Check for errors in previous job
        run: |
          if [ "$(cat test_status.txt)" == "FAILED" ]; then
            echo "Errors found in previous job:"
            cat napaka.txt
            exit 1
          fi
      
      - name: Build tests
        run: |
          cd binaryradix
          g++ -o run_tests binaryradix_test.cpp binaryradix.cpp -lgtest -lgtest_main -pthread
      
      - name: Run tests
        run: |
          cd binaryradix
          ./run_tests
          
      - name: Create test results artifact
        run: |
          echo "Tests passed successfully!" > test_results.txt
          
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test_results.txt
