name: Test C++ Code
on:
  push:
    branches: [master]
  workflow_dispatch: #manually
jobs:
  check_tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: List directory contents
        run: find . -type f -name "*.cpp" | sort
        
      - name: Check if tests exist
        run: |
          if [ ! -f "binaryradix/binaryradix_test.cpp" ]; then
            echo "Error: binaryradix_test.cpp doesn't exist" >&2
            exit 1
          fi
          
          if [ ! -f "binaryradix/binaryradix.cpp" ]; then
            echo "Error: binaryradix.cpp doesn't exist" >&2
            exit 1
          fi
        continue-on-error: true
      
      - name: Redirect stderr to file
        run: ls -la binaryradix/binaryradix_test.cpp 2> napaka.txt || true
      
      - name: Upload error file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: error-log
          path: napaka.txt

  run-tests:
    needs: check_tests
    runs-on: self-hosted
    strategy:
      matrix:
        optimization: [O0, O1, O2, O3]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      
      - name: Download errorlog
        uses: actions/download-artifact@v4
        with:
          name: error-log
      
      - name: Check for errors
        run: |
          if [ -s napaka.txt ]; then
            echo "Errors found in previous job"
            cat napaka.txt
            exit 1
          fi
      
      # - name: Install dependencies
      #   run: |
      #     sudo apt-get install -y build-essential cmake g++ libgtest-dev
      
      - name: Build tests
        run: |
          cd binaryradix
          g++ -${{ matrix.optimization }} -o run_tests_${{ matrix.optimization }} binaryradix_test.cpp binaryradix.cpp -lgtest -lgtest_main -pthread
      
      - name: Run tests
        run: |
          cd binaryradix
          echo "Running tests with optimization level: ${{ matrix.optimization }}"
          ./run_tests_${{ matrix.optimization }}
          
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.optimization }}
          path: binaryradix/run_tests_${{ matrix.optimization }}
