name: Deploy to Docker Hub
on:
  workflow_run:
    workflows: ["TestCppCode"]
    branches: [master]
    types:
      - completed
  workflow_dispatch: # manually
env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      # Remove the attempts to download artifacts from the previous workflow
      
      - name: Log in to Docker Hub
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Create Dockerfile
        run: |
          cat > Dockerfile << 'EOF'
          FROM debian:bullseye-slim
          
          # Install necessary packages
          RUN apt-get update && \
              apt-get install -y --no-install-recommends \
              build-essential \
              g++ \
              libgtest-dev \
              cmake \
              && rm -rf /var/lib/apt/lists/*
          
          # Build and install Google Test
          WORKDIR /usr/src/gtest
          RUN cmake . && \
              make && \
              cp lib/*.a /usr/lib
          
          # Copy the application (using the tested code)
          WORKDIR /app
          COPY ./binaryradix/binaryradix.cpp ./binaryradix/
          COPY ./binaryradix/binaryradix_test.cpp ./binaryradix/
          WORKDIR /app/binaryradix
          
          # Compile the application
          RUN g++ -o run_tests binaryradix_test.cpp binaryradix.cpp -lgtest -lgtest_main -pthread
          
          # Set the entry point
          ENTRYPOINT ["./run_tests"]
          EOF
      
      - name: Build and push Docker image
        run: |
          docker build . --file Dockerfile --tag $DOCKER_USERNAME/binaryradix:latest
          docker push $DOCKER_USERNAME/binaryradix:latest
